### ISSUE TITLE
input_filepath from Google Sheets

### ISSUE THREAD

**Issue by 8thgencore** [defuncart/arb_generator#12]
I would like to know if it is possible to substitute `input_filepath` a link to a csv file instead of a variable https://docs.google.com/spreadsheets

**Comment by defuncart** [comment]
Hi @8thgencore, this currently isn't supported and there is no plans to support this feature request. However if want to download a google spreadsheet as csv, I think this can be achieved by setting the file visible on Google Drive to "Anyone with link can view" and then add a script as part of your project to download the spreadsheet locally as a csv file and then convert as normal using arb_generator.

**Comment by defuncart** [comment]
For an overview of how to generate localization delegates from Google Drive, please see [this article](https://github.com/defuncart/flutter-tips-tricks/blob/main/10-GenerateLocalizationDelegatesFromGoogleDrive/README.md).
