### ISSUE TITLE
possibility to import CSV from Google Sheet

### ISSUE THREAD

**Issue by billyandco** [defuncart/arb_generator#13]
Hi, your project is very interesting and very closed to Google Sheet CSV integration

You will find here how to access to Google Sheet data
https://github.com/aloisdeniel/flutter_sheet_localization/blob/master/flutter_sheet_localization_generator/lib/flutter_sheet_localization_generator.dart

I think we should be able to set the Sheet ID inside the pubspec near the file_path
Let me know what do you think about it ! 
Thank you very much

**Comment by defuncart** [comment]
Hi @billyandco, this was answered in #12. More information can be seen in [this article](https://github.com/defuncart/flutter-tips-tricks/blob/main/10-GenerateLocalizationDelegatesFromGoogleDrive/README.md).
