### ISSUE TITLE
how to generate value parameter or plurals

### ISSUE THREAD

**Issue by hikmawanaz** [defuncart/arb_generator#9]
I have already test to create arb from csv, but it didn't generate the value parameter, and only generate for the description.
Or this library is not support those feature for right now?

**Comment by defuncart** [comment]
Hi @hikmawanaz, have you tried running the example app? There is an example there with a description and plurals etc. If you want a description to be added, then your csv file needs to have at least three columns

```csv
keys;description;en;de
```

and csv settings need to specify `description_index` and `base_index`

```
csv_settings:
    delimiter: ";"
    description_index: 1
    base_index: 2
```

It sounds like that your translations begin on `base_index` 2 but you haven't specified this. Please take a look at the example, and if that doesn't solve your issue, please post your csv file, settings, and log output (if applicable).

**Comment by hikmawanaz** [comment]
Thank you for your advice, yes im already tried to run the example.

But my question is this library support to generate placeholder?
This example from flutter offical docs
![image](https://user-images.githubusercontent.com/20640079/213390175-c13e4e19-eeab-4d0a-b083-ff80527f642d.png)

Or we should add manually

**Comment by defuncart** [comment]
Placeholders aren't currently supported, but values, plurals and descriptions are. In this case you'd need a csv file like:

```csv
keys;description;en
hello;A message with a single parameter;Hello {userName}
```

which would generate

```json
{
  "@@locale": "en",
  "hello": "Hello {userName}",
  "@hello": {
    "description": "A message with a single parameter"
  }
```

**Comment by hikmawanaz** [comment]
Ok thank you for your great support 👍 
I think we can close this issue
